### ISSUE TITLE
Large Icon

### ISSUE THREAD

**Issue by joekerna** [PaulLereverend/NextcloudExtract#1]
When right-clicking on zip file the _Extract here_ row has a pretty large icon

![grafik](https://user-images.githubusercontent.com/23077594/55067073-580fa600-507f-11e9-8248-018577aed2d1.png)

**Comment by PaulLereverend** [comment]
This was a bug with right-click plugin. Should be fixed now. Update and tell me if it works for you.

**Comment by joekerna** [comment]
With 0.3 it looks different but not much better:
![grafik](https://user-images.githubusercontent.com/23077594/55077277-9e70ff00-5097-11e9-927d-78daded50c97.png)

**Comment by PaulLereverend** [comment]
Which version of Nextcloud do you use? I do not have this issue on 15 and 16.

**Comment by joekerna** [comment]
I'm on 15.0.5
PHP 7.3.3
MySQL 10.3.13

Firefox

**Comment by joekerna** [comment]
0.4 solves the issue.

Thanks!
