### ISSUE TITLE
Is this app maintained?

### ISSUE THREAD

**Issue by enoch85** [PaulLereverend/NextcloudExtract#101]
Thanks for a great app! We install it per default in the [Nextcloud VM](https://github.com/nextcloud/vm/). Noitced it's no longer supported, and are just wondering if you still maintain it?

Thanks!

cc @PaulLereverend

**Comment by dimangelid** [comment]
@PaulLereverend 

We are using Nextcloud 25 at our organization and we really need this app.

Are there any plans to make it compatible with Nextcloud 25?

**Comment by hul51u** [comment]
For me it works just fine with NC 25.

**Comment by ojsef39** [comment]
Can someone confirm if the App still works with NC 26?

**Comment by hul51u** [comment]
Yes, for me it also works with NC 26.0.1.

**Comment by ojsef39** [comment]
> Yes, for me it also works with NC 26.0.1.

@hul51u Thank you very much for your feedback ❤️

**Comment by phez** [comment]
I have not had any success with NC 27.0.0 on Debian 10.13. Anyone have this working please advise @PaulLereverend . Happy to donate to get this working. Thanks

**Comment by joshtrichards** [comment]
https://github.com/PaulLereverend/NextcloudExtract/releases/tag/1.3.6
