### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by YoSijo** [PaulLereverend/NextcloudExtract#11]
Please update CHANGELOG.md and keep it up to date. Or can I track the changes in the versions somewhere else? Please don't say `git log`. ;)

**Comment by PaulLereverend** [comment]
You can see the major changes here https://github.com/PaulLereverend/NextcloudExtract/releases

But i'll add a changelog with details.

**Comment by YoSijo** [comment]
Thank you very much, sir. This is definitely helpful and I didn't know it yet.
I'd leave the closing of the issue to you. Think you want to do that when the changelog is up to date.

**Comment by PaulLereverend** [comment]
Done. I will keep it updated on the next releases.
