### ISSUE TITLE
Extract in two steps with tar.gz files

### ISSUE THREAD

**Issue by YoSijo** [PaulLereverend/NextcloudExtract#16]
If I unpack a file like `video_converter.tar.gz` :smile: via right click, then I get a `video_converter.tar` folder. In this folder I find the `video_converter.tar` file which I have to unpack again via right click.
Would it be possible to handle this in one step?

**Comment by PaulLereverend** [comment]
I saw that but I was not sure some peoples would be interested. I will handle this on the next version now that I know it is a good idea.

**Comment by PaulLereverend** [comment]
Done ! a14032665b7c8bf6281c687fd0fd7056be998951
