### ISSUE TITLE
Create release for the owncloud marketplace?

### ISSUE THREAD

**Issue by prsnbrg** [PaulLereverend/NextcloudExtract#22]
Hey,

thanks for merged my pull request.

I know you have to do a lot for a marketplace on ownCloud ([https://marketplace.owncloud.com/](https://marketplace.owncloud.com/) ) release, but I would be very happy if you would do it.

Let me know if I can help, e.g. more testing...

**Comment by PaulLereverend** [comment]
Hi, 

I'm sorry, but I don't want to publish an untested version on OC marketplace. I merged your PR to let anyone use it with ownCloud but I wont offer any support if it's not working. 

I will build and upload it  on github so you can use it.
