### ISSUE TITLE
Use Transifex for translations (and add this repo to Nextcloud on Github) 

### ISSUE THREAD

**Issue by enoch85** [PaulLereverend/NextcloudExtract#33]
As the headline says. Maybe @jospoortvliet can help?

**Comment by enoch85** [comment]
Also ping @MorrisJobke

**Comment by MorrisJobke** [comment]
Translations can also be done without the move

**Comment by enoch85** [comment]
Perfect!

**Comment by enoch85** [comment]
Perfect! Something you would be able to help out with @MorrisJobke?

**Comment by MorrisJobke** [comment]
This is the config: #35. Then @nextcloud-bot needs to be added as contributor and once this happened I will enable the sync job that pushes every night the translations. Keep in mind, that existing translations will be overwritten and need to be added to transifex as this is the source of the translations then.

cc @PaulLereverend

**Comment by enoch85** [comment]
This is now merged

**Comment by enoch85** [comment]
Sorry, @nextcloud-bot needs to be added as well.

**Comment by PaulLereverend** [comment]
@nextcloud-bot has been added

**Comment by enoch85** [comment]
@PaulLereverend Hmm, I don't see that @nextcloud-bot has done any commits yet. Are you sure it's added correctly?

I just checked Transifex and it doesn't seem to show up there either.

**Comment by PaulLereverend** [comment]
I added it as collaborator.
I have "Awaiting nextcloud-bot’s response"

Do I have something else to do ?

**Comment by enoch85** [comment]
@MorrisJobke Do you know?

**Comment by jospoortvliet** [comment]
Morris isn't around, but from what I can see in the documentation:
https://docs.nextcloud.com/server/17/developer_manual/app/view/l10n.html#adding-translations

You best create a ticket in the docker ci repo about this.

**Comment by enoch85** [comment]
@PaulLereverend Maybe you forgot to add push rights (write access)?

**Comment by PaulLereverend** [comment]
Opened a PR according to the manual. It should be ok once merged.

**Comment by MorrisJobke** [comment]
Okay - I merged the PR. Unfortunately the invitation for @nextcloud-bot expired already. Could you invite the bot again? I will accept it then directly and the translations will flow in. :)

**Comment by PaulLereverend** [comment]
Done 0c43ee795b03dd4bd9aa79c23bd55106b17b76c4
