### ISSUE TITLE
German translations not working

### ISSUE THREAD

**Issue by larsziegelmann** [PaulLereverend/NextcloudExtract#37]
We enabled "Extract" on our German Nextcloud server. The extract itself works fine, but the translation doesn't. I tried changing the polite form, but it didn't solve the issue.

Nextcloud Version: 16.0.4

**Comment by prsnbrg** [comment]
The German translation comes with the next release.

**Comment by larsziegelmann** [comment]
Ok, thanks for the quick reply.

**Comment by larsziegelmann** [comment]
To my knowledge, the new Nextcloud version has just been launched. 
So we updated our Nextcloud of course. But the issue is that the "Extract" still remained English.
Is there an update on this issue?

**Comment by prsnbrg** [comment]
The official stores of [Nextcloud](https://apps.nextcloud.com/apps/extract) and [ownCloud](https://marketplace.owncloud.com/apps/extract) do not have the app version with the German translation yet. I'm still waiting for a new app release.
But there are still some small bugs to fix.

**Comment by PaulLereverend** [comment]
App updated with the german translation 😃

**Comment by larsziegelmann** [comment]
Thanks for the help! It works.
