### ISSUE TITLE
Add Gzip and Bzip2 support for tar archives?

### ISSUE THREAD

**Issue by e-alfred** [PaulLereverend/NextcloudExtract#4]
Hello,

it would be great to have support for *.tar.gz and *tar.bz2 (and tar itself) support because a lot of those archives are around on Linux systems especially.

**Comment by PaulLereverend** [comment]
Hello,

it's actually the next feature I plan to implement. It should be released in a few day.

**Comment by PaulLereverend** [comment]
Done ! 23ddabc (require p7zip and p7zip-full)
