### ISSUE TITLE
NC 17 compatibility

### ISSUE THREAD

**Issue by schniepp** [PaulLereverend/NextcloudExtract#42]
At this point, the app has not been released for NC 17. People who upgrade to NC 17, will lose Extract.

**Comment by PaulLereverend** [comment]
I will push an update this week end

**Comment by HFranz** [comment]
any updates here?

**Comment by PaulLereverend** [comment]
I'm truly sorry about the delay. My daytime job takes all my time. But I have a week of vacation at the end of october so it should be done by then.

**Comment by PaulLereverend** [comment]
Updated 😄 Feel free to tell me if something is not working.

**Comment by lmamane** [comment]
Shouldn't this issue be closed since the update is done?
