### ISSUE TITLE
Question: Any plans for creating archives? 

### ISSUE THREAD

**Issue by aproposnix** [PaulLereverend/NextcloudExtract#46]
As a project manager, I often have folders with a lot of files for projects that have been completed. It would be nice to be able to archive those folders in zips/tar.gz etc. Are there any plans to add archiving to this app? NextcloudCompress?

**Comment by PaulLereverend** [comment]
Hi, 
This is a great idea. But i'm afraid i wont be able to work on this in the near future. 
I keep the idea anyway
