### ISSUE TITLE
Support of more formats

### ISSUE THREAD

**Issue by DecaTec** [PaulLereverend/NextcloudExtract#5]
I often use 7zip, so it would be great to see 7z support of this app.

As an idea, could this app make use of the p7zip packages, see [here](https://packages.debian.org/sid/p7zip-full)?
Then you could use a wrapper for 7zip like [this one](https://github.com/PHPGangsta/SevenZipArchive).

Advantage: 7zip can read a lot of formats which then could be handled by the app.

**Comment by PaulLereverend** [comment]
It is planned for the next release that will support tar.gz and several other formats like 7z.

**Comment by PaulLereverend** [comment]
Done ! 23ddabc (require p7zip and p7zip-full)
