### ISSUE TITLE
NC 20 Compatibility

### ISSUE THREAD

**Issue by Wdavery** [PaulLereverend/NextcloudExtract#62]
After a quick test it seems to be working fine, no issues for me.

**Comment by ZehuanZhang** [comment]
Extract component has a bug with NC 20 that can not extract file which from external storage.
The archive file's origin path is not based on a user's root, but the path shown in error is.
❓ This problem is not confirmed to only occurs in NC20

**Comment by PaulLereverend** [comment]
Hi @ZehuanZhang 
Group folders are now supported in the latest version (1.3.0). Can you download it here and confirm it is working so I can push it to the appstore ? https://github.com/PaulLereverend/NextcloudExtract/releases/download/1.3.0/extract.tar.gz

Thank you

**Comment by ZehuanZhang** [comment]
Hi @PaulLereverend 
I have manually upgraded extract to 1.3.0. It is working fine with group folders.

Thanks for your concern and reply.
