### ISSUE TITLE
Error 500 on Nextcloud 21

### ISSUE THREAD

**Issue by cformal** [PaulLereverend/NextcloudExtract#68]
When I click on 'extract here', no matter which format, the extraction fails.
Running in a docker container. No server-side encryption. p7zip, p7zip-full, and unrar are installed correctly.
I would be much appreciated if you could help me on this. Thanks. 
 

{"reqId":"qVNSjTtt0FwZt3VW4fZh","level":3,"time":"2021-02-21T02:56:32+00:00","remoteAddr":"141.101.99.217","user":"test","app":"index","method":"POST","url":"/index.php/apps/extract/ajax/extract.php","message":{"Exception":"Exception","Message":"Call to a member function getLocalFile() on null","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Extract\\Controller\\ExtractionController"},"extract"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Extract\\Controller\\ExtractionController","extract",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"extract.extraction.extract"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/extract/ajax/extract.php"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"Error","Message":"Call to a member function getLocalFile() on null","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/extract/lib/Controller/ExtractionController.php","line":35,"function":"getLocalFile","class":"OC\\Files\\Filesystem","type":"::","args":["//docker-master.zip"]},{"file":"/var/www/html/custom_apps/extract/lib/Controller/ExtractionController.php","line":59,"function":"getFile","class":"OCA\\Extract\\Controller\\ExtractionController","type":"->","args":["/","docker-master.zip"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"extract","class":"OCA\\Extract\\Controller\\ExtractionController","type":"->","args":["docker-master.zip","/","0","zip"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Extract\\Controller\\ExtractionController"},"extract"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Extract\\Controller\\ExtractionController"},"extract"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Extract\\Controller\\ExtractionController","extract",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"extract.extraction.extract"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/extract/ajax/extract.php"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Files/Filesystem.php","Line":557},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68","version":"21.0.0.18"}

**Comment by pxlkng-dev** [comment]
Same issue here. Clean install, all librarys installed, php shell_exec function is allowed and file is not damaged. Seems to be a bug on app-side.

**Comment by PaulLereverend** [comment]
Fixed 9c9c110
