### ISSUE TITLE
Nextcloud 22 App "Extract" cannot be installed because it is not compatible with this version of the server.

### ISSUE THREAD

**Issue by asm301** [PaulLereverend/NextcloudExtract#72]
App "Extract" cannot be installed because it is not compatible with this version of the server.

**Comment by sunjam** [comment]
Are you able to force enable it?

**Comment by asm301** [comment]
Yes if I use --force on the command line it will install and work

**Comment by PaulLereverend** [comment]
Fixed  b95c2bc
