### ISSUE TITLE
Nextcloud 23

### ISSUE THREAD

**Issue by Derkades** [PaulLereverend/NextcloudExtract#78]
Issue for tracking Nextcloud 23 compatibility

**Comment by leonardohlee** [comment]
same issue here

**Comment by manuelkamp** [comment]
is this project dead? we need compatibility to 23 - if it is not continued, please advise the users what to do.

**Comment by PaulLereverend** [comment]
Nextcloud 23 is supported on the latest update (1.3.3). 

This project is not dead but i'm doing this on my free time so there might be some delay. If you want to speed things up, feel free to open a pull request.

**Comment by Derkades** [comment]
Thanks!
