### ISSUE TITLE
403 Forbidden - Logged in user must be an administrator

### ISSUE THREAD

**Issue by HFranz** [PaulLereverend/NextcloudExtract#9]
Extracting with admin role is working fine.

When I try to extract .zip with normal user role, I get:
403 Forbidden with response message {"message":"Der angemeldete Benutzer muss ein Administrator sein"}

**I haven't limited app to special user group.**

**Comment by PaulLereverend** [comment]
Okay I see this issue i'm working on it.

**Comment by PaulLereverend** [comment]
Fixed ! e4eea9da2617c13b93caa31b41f97bbdffde526d

**Comment by HFranz** [comment]
Can you already say in which version it will be fixed?

**Comment by PaulLereverend** [comment]
It is fixed in this beta if you want to test it (delete the app and extract this on nextcloud/apps)
https://github.com/PaulLereverend/NextcloudExtract/releases/download/1.1.5/extract.tar.gz

And it will be available for public once I have run a few more tests.
